<a href="https://colab.research.google.com/github/ArunK-ML/ML-Regression-Model---Concrete-Mix-Strength---Dataset/blob/main/Concrete_Strength.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv("/content/2500 Concrete design mixes.csv")
df

Unnamed: 0 Type_of_course_Aggregate Type_of_Fine_Aggregate_  \
0              0                  Crushed                 Natural   
1              1                  Crushed                 Natural   
2              2                  Crushed                 Natural   
3              3                  Natural                 Natural   
4              4                  Natural                 Natural   
...          ...                      ...                     ...   
2281        2281                        0                       0   
2282        2282                        0                       0   
2283        2283                        0                       0   
2284        2284                        0                       0   
2285        2285                        0                       0   

     Max._Size_of_Coarse_Aggregate_(mm)  Passing_0.6_mm_Sieve_(%)  \
0                                    40                       0.0   
1                                    40                       0.0   
2                                    20                      45.6   
3                                    20                      57.9   
4                                    20                      19.5   
...                                 ...                       ...   
2281                               20.0                       0.0   
2282                               20.0                       0.0   
2283                               20.0                       0.0   
2284                               20.0                       0.0   
2285                                  0                       0.0   

     Target_Mean_Strength_(N/mm2)  Cement_O.P.C_(Kg/m3)  W/C_Ratio  \
0                              43                 365.0       0.52   
1                        CALcrete                 365.0       0.52   
2                              38                 350.0       0.53   
3                              38                 340.0       0.49   
4                              38                 325.0       0.51   
...                           ...                   ...        ...   
2281                         43.0                 375.0       0.45   
2282                         43.0                 365.0       0.51   
2283                         43.0                 385.0       0.47   
2284                         43.0                 340.0       0.47   
2285                            0                   0.0       0.00   

      Water_Content_(Kg/m3) Additive_Type_&_Dosage_(/100_kg_of_cement)  ...  \
0                     225.0                                          0  ...   
1                     225.0                                          0  ...   
2                     185.0                      type SP 801 dos 1 lit  ...   
3                     165.0                            Sp 432 0.9 lit   ...   
4                     165.0                          sp432 dos 1.0 lit  ...   
...                     ...                                        ...  ...   
2281                  170.0                                          0  ...   
2282                  185.0                                          0  ...   
2283                  180.0                                          0  ...   
2284                  160.0                                          0  ...   
2285                    0.0                                          0  ...   

      Workability_Slump_(mm)  Hardened_Concrete_Desnity_(avg.)  7_day_str  \
0                      160.0                            2407.0       21.8   
1                      160.0                            2403.0       26.3   
2                      120.0                            2475.0       32.7   
3                      190.0                            2412.0       30.3   
4                      170.0                            2404.0       27.0   
...                      ...                               ...        ...   
2281               

In [2]:
df.shape

(2286, 23)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2286 entries, 0 to 2285
Data columns (total 23 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   Unnamed: 0                                  2286 non-null   int64  
 1   Type_of_course_Aggregate                    2286 non-null   object 
 2   Type_of_Fine_Aggregate_                     2286 non-null   object 
 3   Max._Size_of_Coarse_Aggregate_(mm)          2286 non-null   object 
 4   Passing_0.6_mm_Sieve_(%)                    2286 non-null   float64
 5   Target_Mean_Strength_(N/mm2)                2286 non-null   object 
 6   Cement_O.P.C_(Kg/m3)                        2286 non-null   float64
 7   W/C_Ratio                                   2286 non-null   float64
 8   Water_Content_(Kg/m3)                       2286 non-null   float64
 9   Additive_Type_&_Dosage_(/100_kg_of_cement)  2286 non-null   object 
 10  Total_Aggreg

In [9]:
df["Target_Mean_Strength_(N/mm2)"].unique()

array(['43', 'CALcrete', '38', '25', '48', '28', '39', '42', '38.0',
       '48.0', '0', '25.0', '39.0', '43.0', '43.1', '40.4', '38.5'],
      dtype=object)

In [10]:
df["Target_Mean_Strength_(N/mm2)"] = df["Target_Mean_Strength_(N/mm2)"].replace({"CALcrete":"35"})

In [12]:
df["Max._Size_of_Coarse_Aggregate_(mm)"].unique()

array(['40', '20', 'n', '0', '20.0', '40.0'], dtype=object)

In [13]:
df["Max._Size_of_Coarse_Aggregate_(mm)"] = df["Max._Size_of_Coarse_Aggregate_(mm)"].replace({"n":"0"})

In [15]:
df["Max._Size_of_Coarse_Aggregate_(mm)"] = df["Max._Size_of_Coarse_Aggregate_(mm)"].astype(float)
df["Target_Mean_Strength_(N/mm2)"] = df["Target_Mean_Strength_(N/mm2)"].astype(float)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2286 entries, 0 to 2285
Data columns (total 23 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   Unnamed: 0                                  2286 non-null   int64  
 1   Type_of_course_Aggregate                    2286 non-null   object 
 2   Type_of_Fine_Aggregate_                     2286 non-null   object 
 3   Max._Size_of_Coarse_Aggregate_(mm)          2286 non-null   float64
 4   Passing_0.6_mm_Sieve_(%)                    2286 non-null   float64
 5   Target_Mean_Strength_(N/mm2)                2286 non-null   float64
 6   Cement_O.P.C_(Kg/m3)                        2286 non-null   float64
 7   W/C_Ratio                                   2286 non-null   float64
 8   Water_Content_(Kg/m3)                       2286 non-null   float64
 9   Additive_Type_&_Dosage_(/100_kg_of_cement)  2286 non-null   object 
 10  Total_Aggreg

In [4]:
df.duplicated().sum()

np.int64(0)

In [6]:
# Add the columns back if dropped earlier
df['Admix_type'].fillna(0, inplace=True)
df['Admix_dosage'].fillna(0, inplace=True)

/tmp/ipython-input-1856587729.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Admix_type'].fillna(0, inplace=True)
/tmp/ipython-input-1856587729.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2286 entries, 0 to 2285
Data columns (total 22 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   Type_of_course_Aggregate                    2286 non-null   int64  
 1   Type_of_Fine_Aggregate_                     2286 non-null   int64  
 2   Max._Size_of_Coarse_Aggregate_(mm)          2286 non-null   float64
 3   Passing_0.6_mm_Sieve_(%)                    2286 non-null   float64
 4   Target_Mean_Strength_(N/mm2)                2286 non-null   float64
 5   Cement_O.P.C_(Kg/m3)                        2286 non-null   float64
 6   W/C_Ratio                                   2286 non-null   float64
 7   Water_Content_(Kg/m3)                       2286 non-null   float64
 8   Additive_Type_&_Dosage_(/100_kg_of_cement)  2286 non-null   int64  
 9   Total_Aggregate_(Kg/m3)                     2286 non-null   float64
 10  Fine_Aggrega

In [23]:
df["Unnamed: 0"].drop()

In [25]:
df["Type_of_course_Aggregate"].unique()

array([1, 2, 0])

In [26]:
df["Type_of_Fine_Aggregate_"].unique()

array([3, 2, 1, 0])

In [37]:
df["Max._Size_of_Coarse_Aggregate_(mm)"].unique()

array([1., 2., 0.])

In [34]:
df['Max._Size_of_Coarse_Aggregate_(mm)'] = df['Max._Size_of_Coarse_Aggregate_(mm)'].replace({
    40.: 1,
    20.: 2,
    0.: 0
})

In [38]:
df['Max._Size_of_Coarse_Aggregate_(mm)'].astype("int")

0       1
1       1
2       2
3       2
4       2
       ..
2281    2
2282    2
2283    2
2284    2
2285    0
Name: Max._Size_of_Coarse_Aggregate_(mm), Length: 2286, dtype: int64

In [28]:
df.to_csv("Concrete_Strength_clean")

# **Encoder**

In [27]:
from sklearn.preprocessing import LabelEncoder
code = LabelEncoder()

for i in df.select_dtypes(include="object").columns:
  df[i] = code.fit_transform(df[i])

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']